services:
  psql_bp:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}

  minio:
    image: minio/minio:latest
    container_name: minio_storage
    restart: unless-stopped
    ports:
      - '9000:9000' # API port
      - '9001:9001' # Console port
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${STORAGE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${STORAGE_SECRET_KEY}
    command: server /data --console-address ":9001"

volumes:
  psql_volume_bp:
  minio_data:
